In [ ]:
help()

Welcome to Python 3.12's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.12/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q" or "quit".



help>  ok


No Python documentation found for 'ok'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



help>  close


No Python documentation found for 'close'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



help>  thanks


No Python documentation found for 'thanks'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [5]:
import ridoy as tur
help(tur)

ModuleNotFoundError: No module named 'ridoy'

In [3]:
import pandas as pd
help(pd)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [ ]:
num = int(input('Enter a number'))

In [1]:
print('Hello')

Hello


In [7]:
print(id('Hello, Python!'))
print(id(3.14))
print(id(1729))

1633184306672
1633166831504
1633183414992


In [9]:
num = int(input('Enter a number: '))
print(f'The entered number is {num}.')
print(eval('num*num'))

Enter a number:  5


The entered number is 5.
25


In [11]:
special_nums = [0.577, 1.618, 2.718, 3.14, 28, 37, 1729]
def division(number):
 return number/number
division_number_iterator = map(division, special_nums)
divided_nums = list(division_number_iterator)
print(divided_nums)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [1]:
is True ?

SyntaxError: invalid syntax (2442398783.py, line 1)

In [3]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'is True ?',
  'import json\nimport getpass\nimport hashlib\n\ndef import_pandas_safely():\n    try:\n        return __import__(\'pandas\')\n    except ImportError:\n        return False\n\n\n__pandas = import_pandas_safely()\n\n\ndef is_data_frame(v: str):\n    obj = eval(v)\n    if  isinstance(obj, __pandas.core.frame.DataFrame) or isinstance(obj, __pandas.core.series.Series):\n        return True\n\n\ndef dataframe_columns(var):\n    df = eval(var)\n    if isinstance(df, __pandas.core.series.Series):\n        return [[df.name, str(df.dtype)]]\n    return list(map(lambda col: [col, str(df[col].dtype)], df.columns))\n\n\ndef dtypes_str(frame):\n    return str(eval(frame).dtypes)\n\ndef dataframe_hash(var):\n   

In [5]:
def function():
    variable= True
    print(variable)
    locals()[variable]=False
    print(variable)

function()

True
True


In [9]:
def dict_1():
    return locals()
def dict_2():
    program='Python'
    return locals()

print('If there is no locals(), it returns an empty dictonary',dict_1())
print('If there is locals(), it returns a dictonary',dict_2())

If there is no locals(), it returns an empty dictonary {}
If there is locals(), it returns a dictonary {'program': 'Python'}


In [19]:
# 'format' function use in python

num =32
print(format(num,'d'))
print(format(num,'f'))
print(format(num, 'b'))
print(format(num, 'x'))
print(format(num, 'o'))

32
32.000000
100000
20
40


In [21]:
print(hex(15))

0xf


In [25]:
print(hex(1729))


0x6c1


In [29]:
num=int(input('Enter a number :'))
print(f'The oct value of {num} is {oct(num)}')

Enter a number : 32


The oct value of 32 is 0o40


In [31]:
text= 'Ridoy'
print(list(text))

['R', 'i', 'd', 'o', 'y']


In [33]:
ba = bytearray('XYZ', 'utf-8')
mv = memoryview(ba)
print(mv)
print(mv[0])
print(mv[1])
print(mv[2])
print(bytes(mv[0:2]))
print(list(mv[:]))
print(set(mv[:]))
print(tuple(mv[:]))
mv[1] = 65 # 'Y' was replaced with 'A'
print(list(mv[:])) 
print(ba)

88
89
90
b'XY'
[88, 89, 90]
{88, 89, 90}
(88, 89, 90)
[88, 65, 90]
bytearray(b'XAZ')


In [39]:
special_nums = [0.577, 1.618, 2.718, 3.14, 6, 28, 37, 1729]
number = iter(special_nums) # Create an iteration
item = next(number) # First item
print(item)
item = next(number) # Second item
print(item)
item = next(number) # Third item, etc
print(item)
item = next(number)
print(item)
item = next(number)
print(item)
item = next(number)
print(item)
item = next(number)
print(item)
item = next(number)
print(item)
# item = next(number)
# print(item)

0.577
1.618
2.718
3.14
6
28
37
1729


In [41]:
path = "authors.txt"
with open(path, "r") as file:
 FileContent = file.read()
 print(FileContent)


FileNotFoundError: [Errno 2] No such file or directory: 'authors.txt'

In [43]:
print(complex(1))
print(complex(2, 2))
print(complex(3.14, 1.618))

(1+0j)
(2+2j)
(3.14+1.618j)


In [45]:
print(divmod(3.14, 0.577))
print(divmod(9, 3))
print(divmod(12, 5))
print(divmod('Hello', 'Python!')) 

(5.0, 0.25500000000000034)
(3, 0)
(2, 2)


TypeError: unsupported operand type(s) for divmod(): 'str' and 'str'

In [57]:
class SpecialNumbers:
 euler_constant = 0.0
 euler_number = 0.0
 pi = 0.0
 golden_ratio = 0
 msg = ''
 
 def __init__(self, euler_constant, euler_number, pi, golden_ratio, msg):
     self.euler_constant = euler_constant
     self.euler_number = euler_number
     self.pi = pi
     self.golden_ratio = golden_ratio
     self.msg = msg
special_numbers = SpecialNumbers(0.577, 2.718, 3.14, 1.618, 'These numbers are special.')
print(special_numbers.euler_constant)
print(special_numbers.euler_number)
print(special_numbers.pi)
print(special_numbers.golden_ratio)
print(special_numbers.msg)
setattr(special_numbers, 'Ramanujan_Hardy_number', 172)
print(special_numbers.Ramanujan_Hardy_number)


0.577
2.718
3.14
1.618
These numbers are special.
172


In [59]:
print(slice(2.718))
print(slice(0.577, 1.618, 3.14))
msg = 'Hello, Python!'
sliced_msg = slice(5)
print(msg[sliced_msg])
special_nums = [0.577, 1.618, 2.718, 3.14, 6, 28, 37, 1729]
sliced_list = slice(4)
print(special_nums[sliced_list])
sliced_list = slice(-1, -6, -2)
print(special_nums[sliced_list])
print(special_nums[0:4]) # Slicing with indexing
print(special_nums[-4:-1])

slice(None, 2.718, None)
slice(0.577, 1.618, 3.14)
Hello
[0.577, 1.618, 2.718, 3.14]
[1729, 28, 3.14]
[0.577, 1.618, 2.718, 3.14]
[6, 28, 37]


In [61]:
special_nums = [2.718, 1729, 0.577, 1.618, 28, 3.14, 6, 37]
print(sorted(special_nums))
txt = 'Hello, Python!'
print(sorted(txt))

[0.577, 1.618, 2.718, 3.14, 6, 28, 37, 1729]
[' ', '!', ',', 'H', 'P', 'e', 'h', 'l', 'l', 'n', 'o', 'o', 't', 'y']


In [65]:
print(ord('9'))
print(ord('X'))
print(ord('W'))
print(ord('^'))
print(ord('a'))

57
88
87
94
97


In [67]:
print(pow(2.718, 3.14))
print(pow(-25, -2))
print(pow(16, 3))
print(pow(-6, 2))
print(pow(6, -2))


23.09634618919156
0.0016
4096
36
0.027777777777777776


In [69]:
txt = 'ToufikeUrRahmanRidoy'
print(list(reversed(txt)))
special_nums = [2.718, 1729, 0.577, 1.618, 28, 3.14, 6, 37]
print(list(reversed(special_nums)))
nums = range(6, 28)
print(list(reversed(nums)))
special_nums_tuple = (2.718, 1729, 0.577, 1.618, 28, 3.14, 6, 37)
print(list(reversed(special_nums_tuple)))

['y', 'o', 'd', 'i', 'R', 'n', 'a', 'm', 'h', 'a', 'R', 'r', 'U', 'e', 'k', 'i', 'f', 'u', 'o', 'T']
[37, 6, 3.14, 28, 1.618, 0.577, 1729, 2.718]
[27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6]
[37, 6, 3.14, 28, 1.618, 0.577, 1729, 2.718]


In [73]:
print(round(3.14))
print(round(2.718))
print(round(0.577))
print(round(1.618))
print(round(1729))
print(round(-1.67))

3
3
1
2
1729
-2


In [83]:
special_nums = [2.718, 1729, 0.577, 1.618, 28, 3.14, 6, 37]
special_nums_tuple = tuple(special_nums)
print(special_nums_tuple)
print(type(special_nums))
print()
txt = 'Hello, Python!'
txt_tuple = tuple(txt)
print(txt_tuple)
print(type(txt))
print()
dictionary = {'A': 0.577, 'B': 2.718, 'C': 3.14}
dictionary_tuple = tuple(dictionary)
print(dictionary_tuple)
print(type(dictionary))
print()
special_nums_set = {2.718, 1729, 0.577, 1.618, 28, 3.14, 6, 37}
special_nums_tuple = tuple(special_nums_set)
print(special_nums_tuple)
print(type(special_nums_set))
print()
class SpecialNumbers:
 euler_constant = 0.577
 euler_number = 2.718
 pi = 3.14
 golden_ratio = 1.618
 msg = 'These numbers are very special'
 
 def __init__(self, euler_constant, euler_number, pi, golden_ratio, msg):
     self.euler_constant = euler_constant
     self.euler_number = euler_number
     self.pi = pi
     self.golden_ratio = golden_ratio
     self.msg = msg
special_numbers = SpecialNumbers(0.577, 2.718, 3.14, 1.618, 'These numbers are very special.')
print(type(special_numbers))

(2.718, 1729, 0.577, 1.618, 28, 3.14, 6, 37)
<class 'list'>

('H', 'e', 'l', 'l', 'o', ',', ' ', 'P', 'y', 't', 'h', 'o', 'n', '!')
<class 'str'>

('A', 'B', 'C')
<class 'dict'>

(0.577, 1729, 2.718, 3.14, 1.618, 37, 6, 28)
<class 'set'>

<class '__main__.SpecialNumbers'>


class SpecialNumbers:
 euler_constant = 0.577
 euler_number = 2.718
 pi = 3.14
 golden_ratio = 1.618
 msg = 'These numbers are very special'
 
 def __init__(self, euler_constant, euler_number, pi, golden_ratio, msg):
 self.euler_constant = euler_constant
 self.euler_number = euler_number
 self.pi = pi
 self.golden_ratio = golden_ratio
 self.msg = msg
special_numbers = SpecialNumbers(0.577, 2.718, 3.14, 1.618, 'These numbers are very special.')
print(vars(special_numbers))

class SpecialNumbers:
 euler_constant = 0.577
 euler_number = 2.718
 pi = 3.14
 golden_ratio = 1.618
 msg = 'These numbers are very special'
 
 def __init__(self, euler_constant, euler_number, pi, golden_ratio, msg):
     self.euler_constant = euler_constant
     self.euler_number = euler_number
     self.pi = pi
     self.golden_ratio = golden_ratio
     self.msg = msg
special_numbers = SpecialNumbers(0.577, 2.718, 3.14, 1.618, 'These numbers are very special.')
print(vars(special_numbers))